import Head from "next/head";
import { useEffect, useState } from "react";
import changeBackColor from "../utils/changeBackColor";
import generateRanNumber from "../utils/randomNumber";

import React from "react";
import Chart from "chart.js";
import CardInfoPpm from "../components/CardInfoPpm";
import LogInForm from "../components/login";

const io = require("socket.io-client");
const socket = io("http://localhost:4000");

export default function Home() {
  let session = false;

  let valorPPM = 0;
  socket.on("humo", function (data) {
    //console.log("DEL SERVER",data)
    valorPPM = data;
  });

  function iniciarSesion() {
    session = !session;
    alert(session)
    console.log(session)
  }

  useEffect(() => {
    var CronJob = require("cron").CronJob;
    var job = new CronJob(
      "* * * * * *",
      function () {
        console.log("Mensaje Cada segundo");
        if (session) {
          changeBackColor(valorPPM);
        }
        //socket.emit("sendPPM", 34);
      },
      null,
      true,
      "America/Los_Angeles"
    );
  });

  return (
    <div>
      <Head>
        <title>DETECCION HUMO</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://cdn.tailwindcss.com"></script>
      </Head>

      {!session && (
        <>
          <p id="valorPPMID" hidden></p>
          <p id="cambiarBack" hidden></p>
          <div class="mb-6">
            <label
              for="email"
              class="block mb-2 text-sm font-medium text-gray-900 dark:text-gray-300"
            >
              Your email
            </label>
            <input
              type="email"
              id="email"
              class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
              placeholder="name@flowbite.com"
              required=""
            />
          </div>
          <div class="mb-6">
            <label
              for="password"
              class="block mb-2 text-sm font-medium text-gray-900 dark:text-gray-300"
            >
              Your password
            </label>
            <input
              type="password"
              id="password"
              class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
              required=""
            />
          </div>
          <div class="flex items-start mb-6">
            <div class="flex items-center h-5">
              <input
                id="remember"
                type="checkbox"
                value=""
                class="w-4 h-4 border border-gray-300 rounded bg-gray-50 focus:ring-3 focus:ring-blue-300 dark:bg-gray-700 dark:border-gray-600 dark:focus:ring-blue-600 dark:ring-offset-gray-800"
                required=""
              />
            </div>
            <label
              for="remember"
              class="ml-2 text-sm font-medium text-gray-900 dark:text-gray-300"
            >
              Remember me
            </label>
          </div>
          <button
            onClick={iniciarSesion()}
            class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800"
          >
            Submit
          </button>
        </>
      )}
      {session && (
        <main
          id="cambiarBack"
          className="w-screen h-screen bg-blue-500  text-center flex flex-col items-center justify-center gap-4"
        >
          <CardInfoPpm />
          <div>
            <a
              className=" bg-gray-200 px-4 py-2 rounded-xl hover:bg-gray-300 shadow"
              href="/streaming"
            >
              Grafico en Tiempo Real
            </a>
          </div>
        </main>
      )}
    </div>
  );
}
